In [149]:
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.preprocessing import MinMaxScaler
from Preprocessing.preprocess import read_data
from scipy.optimize import minimize
import pandas as pd

In [67]:
chicken = pd.read_csv('./Data Lemak/preprocessed/pure fat/chicken/chicken_mean.csv', names=['Wavelength', 'Intensity'])
duck = pd.read_csv('./Data Lemak/preprocessed/pure fat/duck/duck_mean.csv', names=['Wavelength', 'Intensity'])
goat = pd.read_csv('./Data Lemak/preprocessed/pure fat/goat/goat_mean.csv', names=['Wavelength', 'Intensity'])
cow = pd.read_csv('./Data Lemak/preprocessed/pure fat/cow/cow_mean.csv', names=['Wavelength', 'Intensity'])
pig = pd.read_csv('./Data Lemak/preprocessed/pure fat/pig/pig_mean.csv', names=['Wavelength', 'Intensity'])
pig_chicken_25_75 = pd.read_csv('./Data Lemak/preprocessed/contamination/pig-chicken/pig-chicken 25-75/pig_chicken_25_75_all.csv', header=None)
pig_chicken_50_50 = pd.read_csv('./Data Lemak/preprocessed/contamination/pig-chicken/pig-chicken 50-50/pig_chicken_50_50_all.csv', header=None)
pig_chicken_75_25 = pd.read_csv('./Data Lemak/preprocessed/contamination/pig-chicken/pig-chicken 75-25/pig_chicken_75_25_all.csv', header=None)

In [69]:
scaler = MinMaxScaler()
chicken['Intensity'] = scaler.fit_transform(chicken['Intensity'].values.reshape(-1, 1))
cow['Intensity'] = scaler.fit_transform(cow['Intensity'].values.reshape(-1, 1))
duck['Intensity'] = scaler.fit_transform(duck['Intensity'].values.reshape(-1, 1))
goat['Intensity'] = scaler.fit_transform(goat['Intensity'].values.reshape(-1, 1))
pig['Intensity'] = scaler.fit_transform(pig['Intensity'].values.reshape(-1, 1))
for i in range(pig_chicken_25_75.shape[1]):
    pig_chicken_25_75[i] = scaler.fit_transform(pig_chicken_25_75[i].values.reshape(-1, 1))
for i in range(pig_chicken_50_50.shape[1]):
    pig_chicken_50_50[i] = scaler.fit_transform(pig_chicken_50_50[i].values.reshape(-1, 1))
for i in range(pig_chicken_75_25.shape[1]):
    pig_chicken_75_25[i] = scaler.fit_transform(pig_chicken_75_25[i].values.reshape(-1, 1))

# Pig Chicken

## Pig-chicken (25 - 75)

### All variables

In [183]:
components = np.array([chicken['Intensity'], cow['Intensity'], duck['Intensity'], goat['Intensity'], pig['Intensity']])

In [186]:
model = lambda b, x: b[0] * x[:, 0] + b[1] * x[:, 1] + b[2] * x[:, 2] + b[3] * x[:, 3] + b[4] * x[:, 4]
obj = lambda b, y, x: np.sum((y - model(b, x)) ** 2)
bnds = ((0, 1), (0, 1), (0, 1), (0, 1), (0, 1))
cons = [{'type': 'eq', 'fun': lambda b: 1 - np.sum(b)}]
x_init = np.array([0., 0., 0., 0., 0.])
coef = []
for i in range(1, pig_chicken_25_75.shape[1]):
    res = minimize(obj, x_init, args=(pig_chicken_25_75.iloc[:, i].values, components.T), bounds=bnds, constraints=cons)
    coef.append(res.x)

In [187]:
pd.DataFrame(coef, columns=['chicken', 'cow', 'duck', 'goat', 'pig']).round(3).head(10)

   chicken    cow   duck  goat    pig
0    0.930  0.055  0.015   0.0  0.000
1    1.000  0.000  0.000   0.0  0.000
2    0.815  0.057  0.128   0.0  0.000
3    1.000  0.000  0.000   0.0  0.000
4    0.819  0.000  0.144   0.0  0.037
5    1.000  0.000  0.000   0.0  0.000
6    0.949  0.051  0.000   0.0  0.000
7    1.000  0.000  0.000   0.0  0.000
8    0.980  0.012  0.004   0.0  0.004
9    0.576  0.087  0.279   0.0  0.058

### 2 Variables

In [188]:
components = np.array([chicken['Intensity'], pig['Intensity']])

In [189]:
model = lambda b, x: b[0] * x[:, 0] + b[1] * x[:, 1]
obj = lambda b, y, x: np.sum((y - model(b, x)) ** 2)
bnds = ((0, 1), (0, 1))
cons = [{'type': 'eq', 'fun': lambda b: 1 - np.sum(b)}]
x_init = np.array([0., 0.])
coef = []
for i in range(1, pig_chicken_25_75.shape[1]):
    res = minimize(obj, x_init, args=(pig_chicken_25_75.iloc[:, i].values, components.T), bounds=bnds, constraints=cons)
    coef.append(res.x)

In [190]:
pd.DataFrame(coef, columns=['chicken', 'pig']).round(3).head(10)

   chicken    pig
0    0.963  0.037
1    1.000  0.000
2    0.884  0.116
3    1.000  0.000
4    0.902  0.098
5    1.000  0.000
6    0.990  0.010
7    1.000  0.000
8    0.980  0.020
9    0.726  0.274

## Pig-chicken (50 - 50)

### All variables

In [191]:
components = np.array([chicken['Intensity'], cow['Intensity'], duck['Intensity'], goat['Intensity'], pig['Intensity']])

In [192]:
model = lambda b, x: b[0] * x[:, 0] + b[1] * x[:, 1] + b[2] * x[:, 2] + b[3] * x[:, 3] + b[4] * x[:, 4]
obj = lambda b, y, x: np.sum((y - model(b, x)) ** 2)
bnds = ((0, 1), (0, 1), (0, 1), (0, 1), (0, 1))
cons = [{'type': 'eq', 'fun': lambda b: 1 - np.sum(b)}]
x_init = np.array([0., 0., 0., 0., 0.])
coef = []
for i in range(1, pig_chicken_50_50.shape[1]):
    res = minimize(obj, x_init, args=(pig_chicken_50_50.iloc[:, i].values, components.T), bounds=bnds, constraints=cons)
    coef.append(res.x)

In [193]:
pd.DataFrame(coef, columns=['chicken', 'cow', 'duck', 'goat', 'pig']).round(3).head(10)

   chicken    cow   duck  goat  pig
0    0.008  0.047  0.944   0.0  0.0
1    0.000  0.000  1.000   0.0  0.0
2    0.000  0.000  1.000   0.0  0.0
3    0.334  0.050  0.616   0.0  0.0
4    0.558  0.000  0.442   0.0  0.0
5    0.534  0.259  0.207   0.0  0.0
6    0.081  0.000  0.919   0.0  0.0
7    0.389  0.018  0.593   0.0  0.0
8    0.134  0.000  0.866   0.0  0.0
9    0.248  0.000  0.752   0.0  0.0

### 2 Variables

In [194]:
components = np.array([chicken['Intensity'], pig['Intensity']])

In [195]:
model = lambda b, x: b[0] * x[:, 0] + b[1] * x[:, 1]
obj = lambda b, y, x: np.sum((y - model(b, x)) ** 2)
bnds = ((0, 1), (0, 1))
cons = [{'type': 'eq', 'fun': lambda b: 1 - np.sum(b)}]
x_init = np.array([0., 0.])
coef = []
for i in range(1, pig_chicken_50_50.shape[1]):
    res = minimize(obj, x_init, args=(pig_chicken_50_50.iloc[:, i].values, components.T), bounds=bnds, constraints=cons)
    coef.append(res.x)

In [196]:
pd.DataFrame(coef, columns=['chicken', 'pig']).round(3).head(10)

   chicken    pig
0    0.682  0.318
1    0.674  0.326
2    0.671  0.329
3    0.816  0.184
4    0.928  0.072
5    0.671  0.329
6    0.752  0.248
7    0.873  0.127
8    0.746  0.254
9    0.825  0.175

## Pig-chicken (75 - 25)

### All variables

In [197]:
components = np.array([chicken['Intensity'], cow['Intensity'], duck['Intensity'], goat['Intensity'], pig['Intensity']])

In [198]:
model = lambda b, x: b[0] * x[:, 0] + b[1] * x[:, 1] + b[2] * x[:, 2] + b[3] * x[:, 3] + b[4] * x[:, 4]
obj = lambda b, y, x: np.sum((y - model(b, x)) ** 2)
bnds = ((0, 1), (0, 1), (0, 1), (0, 1), (0, 1))
cons = [{'type': 'eq', 'fun': lambda b: 1 - np.sum(b)}]
x_init = np.array([0., 0., 0., 0., 0.])
coef = []
for i in range(1, pig_chicken_75_25.shape[1]):
    res = minimize(obj, x_init, args=(pig_chicken_75_25.iloc[:, i].values, components.T), bounds=bnds, constraints=cons)
    coef.append(res.x)

In [199]:
pd.DataFrame(coef, columns=['chicken', 'cow', 'duck', 'goat', 'pig']).round(3).head(10)

   chicken    cow   duck   goat    pig
0    0.000  0.001  0.000  0.198  0.801
1    0.000  0.069  0.000  0.166  0.765
2    0.278  0.024  0.000  0.085  0.613
3    0.000  0.000  0.000  0.243  0.757
4    0.000  0.000  0.000  0.189  0.811
5    0.000  0.000  0.000  0.142  0.858
6    0.362  0.000  0.000  0.120  0.517
7    0.404  0.000  0.596  0.000  0.000
8    0.284  0.001  0.000  0.282  0.433
9    0.000  0.000  0.000  0.254  0.746

### 2 Variables

In [200]:
components = np.array([chicken['Intensity'], pig['Intensity']])

In [201]:
model = lambda b, x: b[0] * x[:, 0] + b[1] * x[:, 1]
obj = lambda b, y, x: np.sum((y - model(b, x)) ** 2)
bnds = ((0, 1), (0, 1))
cons = [{'type': 'eq', 'fun': lambda b: 1 - np.sum(b)}]
x_init = np.array([0., 0.])
coef = []
for i in range(1, pig_chicken_75_25.shape[1]):
    res = minimize(obj, x_init, args=(pig_chicken_75_25.iloc[:, i].values, components.T), bounds=bnds, constraints=cons)
    coef.append(res.x)

In [202]:
pd.DataFrame(coef, columns=['chicken', 'pig']).round(3).head(10)

   chicken    pig
0    0.000  1.000
1    0.000  1.000
2    0.099  0.901
3    0.000  1.000
4    0.000  1.000
5    0.000  1.000
6    0.115  0.885
7    0.905  0.095
8    0.000  1.000
9    0.000  1.000